//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://api.chartlyrics.com/", ClrNamespace="api.chartlyrics.com")]

namespace api.chartlyrics.com
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchLyricResult", Namespace="http://api.chartlyrics.com/")]
    public partial class SearchLyricResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TrackChecksumField;
        
        private int TrackIdField;
        
        private string LyricChecksumField;
        
        private int LyricIdField;
        
        private string SongUrlField;
        
        private string ArtistUrlField;
        
        private string ArtistField;
        
        private string SongField;
        
        private int SongRankField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TrackChecksum
        {
            get
            {
                return this.TrackChecksumField;
            }
            set
            {
                this.TrackChecksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TrackId
        {
            get
            {
                return this.TrackIdField;
            }
            set
            {
                this.TrackIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LyricChecksum
        {
            get
            {
                return this.LyricChecksumField;
            }
            set
            {
                this.LyricChecksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int LyricId
        {
            get
            {
                return this.LyricIdField;
            }
            set
            {
                this.LyricIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SongUrl
        {
            get
            {
                return this.SongUrlField;
            }
            set
            {
                this.SongUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ArtistUrl
        {
            get
            {
                return this.ArtistUrlField;
            }
            set
            {
                this.ArtistUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Artist
        {
            get
            {
                return this.ArtistField;
            }
            set
            {
                this.ArtistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Song
        {
            get
            {
                return this.SongField;
            }
            set
            {
                this.SongField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int SongRank
        {
            get
            {
                return this.SongRankField;
            }
            set
            {
                this.SongRankField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetLyricResult", Namespace="http://api.chartlyrics.com/")]
    public partial class GetLyricResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string TrackChecksumField;
        
        private int TrackIdField;
        
        private string LyricChecksumField;
        
        private int LyricIdField;
        
        private string LyricSongField;
        
        private string LyricArtistField;
        
        private string LyricUrlField;
        
        private string LyricCovertArtUrlField;
        
        private int LyricRankField;
        
        private string LyricCorrectUrlField;
        
        private string LyricField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TrackChecksum
        {
            get
            {
                return this.TrackChecksumField;
            }
            set
            {
                this.TrackChecksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TrackId
        {
            get
            {
                return this.TrackIdField;
            }
            set
            {
                this.TrackIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LyricChecksum
        {
            get
            {
                return this.LyricChecksumField;
            }
            set
            {
                this.LyricChecksumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int LyricId
        {
            get
            {
                return this.LyricIdField;
            }
            set
            {
                this.LyricIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LyricSong
        {
            get
            {
                return this.LyricSongField;
            }
            set
            {
                this.LyricSongField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string LyricArtist
        {
            get
            {
                return this.LyricArtistField;
            }
            set
            {
                this.LyricArtistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string LyricUrl
        {
            get
            {
                return this.LyricUrlField;
            }
            set
            {
                this.LyricUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string LyricCovertArtUrl
        {
            get
            {
                return this.LyricCovertArtUrlField;
            }
            set
            {
                this.LyricCovertArtUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int LyricRank
        {
            get
            {
                return this.LyricRankField;
            }
            set
            {
                this.LyricRankField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string LyricCorrectUrl
        {
            get
            {
                return this.LyricCorrectUrlField;
            }
            set
            {
                this.LyricCorrectUrlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string Lyric
        {
            get
            {
                return this.LyricField;
            }
            set
            {
                this.LyricField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://api.chartlyrics.com/", ConfigurationName="apiv1Soap")]
public interface apiv1Soap
{
    
    // CODEGEN: Generating message contract since element name artist from namespace http://api.chartlyrics.com/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/SearchLyric", ReplyAction="*")]
    SearchLyricResponse SearchLyric(SearchLyricRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/SearchLyric", ReplyAction="*")]
    System.Threading.Tasks.Task<SearchLyricResponse> SearchLyricAsync(SearchLyricRequest request);
    
    // CODEGEN: Generating message contract since element name lyricText from namespace http://api.chartlyrics.com/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/SearchLyricText", ReplyAction="*")]
    SearchLyricTextResponse SearchLyricText(SearchLyricTextRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/SearchLyricText", ReplyAction="*")]
    System.Threading.Tasks.Task<SearchLyricTextResponse> SearchLyricTextAsync(SearchLyricTextRequest request);
    
    // CODEGEN: Generating message contract since element name lyricCheckSum from namespace http://api.chartlyrics.com/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/GetLyric", ReplyAction="*")]
    GetLyricResponse GetLyric(GetLyricRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/GetLyric", ReplyAction="*")]
    System.Threading.Tasks.Task<GetLyricResponse> GetLyricAsync(GetLyricRequest request);
    
    // CODEGEN: Generating message contract since element name trackCheckSum from namespace http://api.chartlyrics.com/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/AddLyric", ReplyAction="*")]
    AddLyricResponse AddLyric(AddLyricRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/AddLyric", ReplyAction="*")]
    System.Threading.Tasks.Task<AddLyricResponse> AddLyricAsync(AddLyricRequest request);
    
    // CODEGEN: Generating message contract since element name artist from namespace http://api.chartlyrics.com/ is not marked nillable
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/SearchLyricDirect", ReplyAction="*")]
    SearchLyricDirectResponse SearchLyricDirect(SearchLyricDirectRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://api.chartlyrics.com/SearchLyricDirect", ReplyAction="*")]
    System.Threading.Tasks.Task<SearchLyricDirectResponse> SearchLyricDirectAsync(SearchLyricDirectRequest request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SearchLyricRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchLyric", Namespace="http://api.chartlyrics.com/", Order=0)]
    public SearchLyricRequestBody Body;
    
    public SearchLyricRequest()
    {
    }
    
    public SearchLyricRequest(SearchLyricRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class SearchLyricRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string artist;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string song;
    
    public SearchLyricRequestBody()
    {
    }
    
    public SearchLyricRequestBody(string artist, string song)
    {
        this.artist = artist;
        this.song = song;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SearchLyricResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchLyricResponse", Namespace="http://api.chartlyrics.com/", Order=0)]
    public SearchLyricResponseBody Body;
    
    public SearchLyricResponse()
    {
    }
    
    public SearchLyricResponse(SearchLyricResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class SearchLyricResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public api.chartlyrics.com.SearchLyricResult[] SearchLyricResult;
    
    public SearchLyricResponseBody()
    {
    }
    
    public SearchLyricResponseBody(api.chartlyrics.com.SearchLyricResult[] SearchLyricResult)
    {
        this.SearchLyricResult = SearchLyricResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SearchLyricTextRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchLyricText", Namespace="http://api.chartlyrics.com/", Order=0)]
    public SearchLyricTextRequestBody Body;
    
    public SearchLyricTextRequest()
    {
    }
    
    public SearchLyricTextRequest(SearchLyricTextRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class SearchLyricTextRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string lyricText;
    
    public SearchLyricTextRequestBody()
    {
    }
    
    public SearchLyricTextRequestBody(string lyricText)
    {
        this.lyricText = lyricText;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SearchLyricTextResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchLyricTextResponse", Namespace="http://api.chartlyrics.com/", Order=0)]
    public SearchLyricTextResponseBody Body;
    
    public SearchLyricTextResponse()
    {
    }
    
    public SearchLyricTextResponse(SearchLyricTextResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class SearchLyricTextResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public api.chartlyrics.com.SearchLyricResult[] SearchLyricTextResult;
    
    public SearchLyricTextResponseBody()
    {
    }
    
    public SearchLyricTextResponseBody(api.chartlyrics.com.SearchLyricResult[] SearchLyricTextResult)
    {
        this.SearchLyricTextResult = SearchLyricTextResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetLyricRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLyric", Namespace="http://api.chartlyrics.com/", Order=0)]
    public GetLyricRequestBody Body;
    
    public GetLyricRequest()
    {
    }
    
    public GetLyricRequest(GetLyricRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class GetLyricRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public int lyricId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string lyricCheckSum;
    
    public GetLyricRequestBody()
    {
    }
    
    public GetLyricRequestBody(int lyricId, string lyricCheckSum)
    {
        this.lyricId = lyricId;
        this.lyricCheckSum = lyricCheckSum;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class GetLyricResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLyricResponse", Namespace="http://api.chartlyrics.com/", Order=0)]
    public GetLyricResponseBody Body;
    
    public GetLyricResponse()
    {
    }
    
    public GetLyricResponse(GetLyricResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class GetLyricResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public api.chartlyrics.com.GetLyricResult GetLyricResult;
    
    public GetLyricResponseBody()
    {
    }
    
    public GetLyricResponseBody(api.chartlyrics.com.GetLyricResult GetLyricResult)
    {
        this.GetLyricResult = GetLyricResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AddLyricRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLyric", Namespace="http://api.chartlyrics.com/", Order=0)]
    public AddLyricRequestBody Body;
    
    public AddLyricRequest()
    {
    }
    
    public AddLyricRequest(AddLyricRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class AddLyricRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
    public int trackId;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string trackCheckSum;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
    public string lyric;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
    public string email;
    
    public AddLyricRequestBody()
    {
    }
    
    public AddLyricRequestBody(int trackId, string trackCheckSum, string lyric, string email)
    {
        this.trackId = trackId;
        this.trackCheckSum = trackCheckSum;
        this.lyric = lyric;
        this.email = email;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class AddLyricResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="AddLyricResponse", Namespace="http://api.chartlyrics.com/", Order=0)]
    public AddLyricResponseBody Body;
    
    public AddLyricResponse()
    {
    }
    
    public AddLyricResponse(AddLyricResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class AddLyricResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string AddLyricResult;
    
    public AddLyricResponseBody()
    {
    }
    
    public AddLyricResponseBody(string AddLyricResult)
    {
        this.AddLyricResult = AddLyricResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SearchLyricDirectRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchLyricDirect", Namespace="http://api.chartlyrics.com/", Order=0)]
    public SearchLyricDirectRequestBody Body;
    
    public SearchLyricDirectRequest()
    {
    }
    
    public SearchLyricDirectRequest(SearchLyricDirectRequestBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class SearchLyricDirectRequestBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public string artist;
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
    public string song;
    
    public SearchLyricDirectRequestBody()
    {
    }
    
    public SearchLyricDirectRequestBody(string artist, string song)
    {
        this.artist = artist;
        this.song = song;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class SearchLyricDirectResponse
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Name="SearchLyricDirectResponse", Namespace="http://api.chartlyrics.com/", Order=0)]
    public SearchLyricDirectResponseBody Body;
    
    public SearchLyricDirectResponse()
    {
    }
    
    public SearchLyricDirectResponse(SearchLyricDirectResponseBody Body)
    {
        this.Body = Body;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.Runtime.Serialization.DataContractAttribute(Namespace="http://api.chartlyrics.com/")]
public partial class SearchLyricDirectResponseBody
{
    
    [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
    public api.chartlyrics.com.GetLyricResult SearchLyricDirectResult;
    
    public SearchLyricDirectResponseBody()
    {
    }
    
    public SearchLyricDirectResponseBody(api.chartlyrics.com.GetLyricResult SearchLyricDirectResult)
    {
        this.SearchLyricDirectResult = SearchLyricDirectResult;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface apiv1SoapChannel : apiv1Soap, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class apiv1SoapClient : System.ServiceModel.ClientBase<apiv1Soap>, apiv1Soap
{
    
    public apiv1SoapClient()
    {
    }
    
    public apiv1SoapClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public apiv1SoapClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public apiv1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public apiv1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SearchLyricResponse apiv1Soap.SearchLyric(SearchLyricRequest request)
    {
        return base.Channel.SearchLyric(request);
    }
    
    public api.chartlyrics.com.SearchLyricResult[] SearchLyric(string artist, string song)
    {
        SearchLyricRequest inValue = new SearchLyricRequest();
        inValue.Body = new SearchLyricRequestBody();
        inValue.Body.artist = artist;
        inValue.Body.song = song;
        SearchLyricResponse retVal = ((apiv1Soap)(this)).SearchLyric(inValue);
        return retVal.Body.SearchLyricResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SearchLyricResponse> apiv1Soap.SearchLyricAsync(SearchLyricRequest request)
    {
        return base.Channel.SearchLyricAsync(request);
    }
    
    public System.Threading.Tasks.Task<SearchLyricResponse> SearchLyricAsync(string artist, string song)
    {
        SearchLyricRequest inValue = new SearchLyricRequest();
        inValue.Body = new SearchLyricRequestBody();
        inValue.Body.artist = artist;
        inValue.Body.song = song;
        return ((apiv1Soap)(this)).SearchLyricAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SearchLyricTextResponse apiv1Soap.SearchLyricText(SearchLyricTextRequest request)
    {
        return base.Channel.SearchLyricText(request);
    }
    
    public api.chartlyrics.com.SearchLyricResult[] SearchLyricText(string lyricText)
    {
        SearchLyricTextRequest inValue = new SearchLyricTextRequest();
        inValue.Body = new SearchLyricTextRequestBody();
        inValue.Body.lyricText = lyricText;
        SearchLyricTextResponse retVal = ((apiv1Soap)(this)).SearchLyricText(inValue);
        return retVal.Body.SearchLyricTextResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SearchLyricTextResponse> apiv1Soap.SearchLyricTextAsync(SearchLyricTextRequest request)
    {
        return base.Channel.SearchLyricTextAsync(request);
    }
    
    public System.Threading.Tasks.Task<SearchLyricTextResponse> SearchLyricTextAsync(string lyricText)
    {
        SearchLyricTextRequest inValue = new SearchLyricTextRequest();
        inValue.Body = new SearchLyricTextRequestBody();
        inValue.Body.lyricText = lyricText;
        return ((apiv1Soap)(this)).SearchLyricTextAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    GetLyricResponse apiv1Soap.GetLyric(GetLyricRequest request)
    {
        return base.Channel.GetLyric(request);
    }
    
    public api.chartlyrics.com.GetLyricResult GetLyric(int lyricId, string lyricCheckSum)
    {
        GetLyricRequest inValue = new GetLyricRequest();
        inValue.Body = new GetLyricRequestBody();
        inValue.Body.lyricId = lyricId;
        inValue.Body.lyricCheckSum = lyricCheckSum;
        GetLyricResponse retVal = ((apiv1Soap)(this)).GetLyric(inValue);
        return retVal.Body.GetLyricResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<GetLyricResponse> apiv1Soap.GetLyricAsync(GetLyricRequest request)
    {
        return base.Channel.GetLyricAsync(request);
    }
    
    public System.Threading.Tasks.Task<GetLyricResponse> GetLyricAsync(int lyricId, string lyricCheckSum)
    {
        GetLyricRequest inValue = new GetLyricRequest();
        inValue.Body = new GetLyricRequestBody();
        inValue.Body.lyricId = lyricId;
        inValue.Body.lyricCheckSum = lyricCheckSum;
        return ((apiv1Soap)(this)).GetLyricAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    AddLyricResponse apiv1Soap.AddLyric(AddLyricRequest request)
    {
        return base.Channel.AddLyric(request);
    }
    
    public string AddLyric(int trackId, string trackCheckSum, string lyric, string email)
    {
        AddLyricRequest inValue = new AddLyricRequest();
        inValue.Body = new AddLyricRequestBody();
        inValue.Body.trackId = trackId;
        inValue.Body.trackCheckSum = trackCheckSum;
        inValue.Body.lyric = lyric;
        inValue.Body.email = email;
        AddLyricResponse retVal = ((apiv1Soap)(this)).AddLyric(inValue);
        return retVal.Body.AddLyricResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<AddLyricResponse> apiv1Soap.AddLyricAsync(AddLyricRequest request)
    {
        return base.Channel.AddLyricAsync(request);
    }
    
    public System.Threading.Tasks.Task<AddLyricResponse> AddLyricAsync(int trackId, string trackCheckSum, string lyric, string email)
    {
        AddLyricRequest inValue = new AddLyricRequest();
        inValue.Body = new AddLyricRequestBody();
        inValue.Body.trackId = trackId;
        inValue.Body.trackCheckSum = trackCheckSum;
        inValue.Body.lyric = lyric;
        inValue.Body.email = email;
        return ((apiv1Soap)(this)).AddLyricAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    SearchLyricDirectResponse apiv1Soap.SearchLyricDirect(SearchLyricDirectRequest request)
    {
        return base.Channel.SearchLyricDirect(request);
    }
    
    public api.chartlyrics.com.GetLyricResult SearchLyricDirect(string artist, string song)
    {
        SearchLyricDirectRequest inValue = new SearchLyricDirectRequest();
        inValue.Body = new SearchLyricDirectRequestBody();
        inValue.Body.artist = artist;
        inValue.Body.song = song;
        SearchLyricDirectResponse retVal = ((apiv1Soap)(this)).SearchLyricDirect(inValue);
        return retVal.Body.SearchLyricDirectResult;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<SearchLyricDirectResponse> apiv1Soap.SearchLyricDirectAsync(SearchLyricDirectRequest request)
    {
        return base.Channel.SearchLyricDirectAsync(request);
    }
    
    public System.Threading.Tasks.Task<SearchLyricDirectResponse> SearchLyricDirectAsync(string artist, string song)
    {
        SearchLyricDirectRequest inValue = new SearchLyricDirectRequest();
        inValue.Body = new SearchLyricDirectRequestBody();
        inValue.Body.artist = artist;
        inValue.Body.song = song;
        return ((apiv1Soap)(this)).SearchLyricDirectAsync(inValue);
    }
}
