//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITunes.Editor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITunes.Editor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder.
        /// </summary>
        public static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music
        ///Music|African
        ///Music|African|African Dancehall
        ///Music|African|African Reggae
        ///Music|African|Afrikaans
        ///Music|African|Afro House
        ///Music|African|Afro Soul
        ///Music|African|Afro-Beat
        ///Music|African|Afro-folk
        ///Music|African|Afro-fusion
        ///Music|African|Afro-Pop
        ///Music|African|Afrobeats
        ///Music|African|Alte
        ///Music|African|Amapiano
        ///Music|African|Benga
        ///Music|African|Bongo-Flava
        ///Music|African|Coupé-Décalé
        ///Music|African|Gqom
        ///Music|African|Highlife
        ///Music|African|Kizomba
        ///Music|African|Kuduro
        ///Music|African|Kw [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting lyics for {Song}.
        /// </summary>
        public static string GettingLyrics {
            get {
                return ResourceManager.GetString("GettingLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Lyrics found, expected {Expected}, but got {Reply}.
        /// </summary>
        public static string IncorrectLyricsFound {
            get {
                return ResourceManager.GetString("IncorrectLyricsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PList value type.
        /// </summary>
        public static string InvalidPListValueType {
            get {
                return ResourceManager.GetString("InvalidPListValueType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid XML.
        /// </summary>
        public static string InvalidXml {
            get {
                return ResourceManager.GetString("InvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lyrics found for {Song}.
        /// </summary>
        public static string NoLyricsFound {
            get {
                return ResourceManager.GetString("NoLyricsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PList.
        /// </summary>
        public static string PListName {
            get {
                return ResourceManager.GetString("PListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed NoLyrics tag for {Song}.
        /// </summary>
        public static string RemovedNoLyricsTag {
            get {
                return ResourceManager.GetString("RemovedNoLyricsTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving {Song} with no lyrics, and unrated.
        /// </summary>
        public static string SavingWithNoLyricsAndUnrated {
            get {
                return ResourceManager.GetString("SavingWithNoLyricsAndUnrated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting lyrics on {Song} to null.
        /// </summary>
        public static string SettingLyricsToNull {
            get {
                return ResourceManager.GetString("SettingLyricsToNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not contain a PList.
        /// </summary>
        public static string StreamDoesNotContainAPList {
            get {
                return ResourceManager.GetString("StreamDoesNotContainAPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated cleaned lyrics for {Song}.
        /// </summary>
        public static string UpdatedCleanedLyrics {
            get {
                return ResourceManager.GetString("UpdatedCleanedLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated lyrics for {Song}.
        /// </summary>
        public static string UpdatedLyrics {
            get {
                return ResourceManager.GetString("UpdatedLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Rating for {Song}.
        /// </summary>
        public static string UpdatedRating {
            get {
                return ResourceManager.GetString("UpdatedRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated BPM in {Song} to {Bpm}.
        /// </summary>
        public static string UpdatingBeatsPerMinute {
            get {
                return ResourceManager.GetString("UpdatingBeatsPerMinute", resourceCulture);
            }
        }
    }
}
